sudo: required
language: bash
services:
  - docker

before_script:
  - docker -v

script:
  - docker build -t keboola/split-by-value-processor .
  - docker run keboola/split-by-value-processor /bin/bash -c "composer install --no-interaction --no-progress && composer ci"

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
